---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Für Cloud Volumes ONTAP sind verschiedene Lizenzierungsoptionen verfügbar. Mit jeder Option können Sie eine Konfiguration wählen, die Ihren Anforderungen entspricht. 
---
= Cloud Volumes ONTAP Lizenzierung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Für Cloud Volumes ONTAP sind verschiedene Lizenzierungsoptionen verfügbar. Jede Option ermöglicht Ihnen, ein Nutzungsmodell auszuwählen, das Ihren Anforderungen entspricht.



== Übersicht über die Lizenzierung

Die folgenden Lizenzierungsoptionen stehen für Neukunden zur Verfügung.

Kapazitätsbasierte Lizenzierung:: Bezahlen Sie für mehrere Cloud Volumes ONTAP Systeme Ihres NetApp Kontos durch bereitgestellte Kapazität. Mit der Möglichkeit, zusätzliche Cloud-Datenservices zu erwerben
Keystone Abonnement:: Ein abonnementbasierter Pay-as-you-grow-Service, der ein nahtloses Hybrid-Cloud-Erlebnis für HA-Paare (High Availability, Hochverfügbarkeit) bietet.


In den folgenden Abschnitten werden die einzelnen Optionen näher beschrieben.


NOTE: Ohne Lizenz ist kein Support für die Nutzung lizenzierter Funktionen verfügbar.



== Kapazitätsbasierte Lizenzierung

Mit kapazitätsbasierten Lizenzpaketen können Sie für Cloud Volumes ONTAP pro tib Kapazität bezahlen. Die Lizenz ist mit Ihrem NetApp Konto verknüpft und ermöglicht es Ihnen, mehrere Systeme gegen die Lizenz aufzuladen, solange über die Lizenz genügend Kapazität verfügbar ist.

Beispielsweise könnten Sie eine einzelne 20-tib-Lizenz erwerben, vier Cloud Volumes ONTAP Systeme implementieren und jedem System dann ein 5-tib-Volume zuweisen, also insgesamt 20 tib. Die Kapazität ist für die Volumes auf jedem in diesem Konto implementierten Cloud Volumes ONTAP System verfügbar.

Kapazitätsbasierte Lizenzierung ist in Form eines _package_ erhältlich. Bei der Implementierung eines Cloud Volumes ONTAP Systems haben Sie die Möglichkeit, je nach Ihren geschäftlichen Anforderungen aus mehreren Lizenzierungspaketen auszuwählen.


NOTE: Während die tatsächliche Nutzung und Nutzungsmessung für die in BlueXP gemanagten Produkte und Services immer in gib und tib berechnet werden, werden die Begriffe GB/gib und TB/tib synonym verwendet. Dies spiegelt sich in den Angeboten, Preisangeboten, Listenbeschreibungen und anderen Begleitdokumenten des Cloud Marketplace wider.



=== Pakete

Die folgenden kapazitätsbasierten Pakete stehen für Cloud Volumes ONTAP zur Verfügung.

Eine Liste der unterstützten VM-Typen mit den folgenden kapazitätsbasierten Paketen finden Sie unter:

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Unterstützte Konfigurationen in Azure"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Unterstützte Konfigurationen in Google Cloud"^]


endif::gcp[]



==== Freimium

Bietet alle Cloud Volumes ONTAP-Funktionen kostenlos von NetApp an (Gebühren für Cloud-Provider gelten noch).

* Lizenz oder Vertrag sind nicht erforderlich.
* Support von NetApp ist nicht inbegriffen.
* Sie sind auf 500 gib der bereitgestellten Kapazität pro Cloud Volumes ONTAP System begrenzt.
* Sie können bis zu 10 Cloud Volumes ONTAP Systeme mit Freemium-Angebot pro NetApp Konto bei jedem Cloud-Provider nutzen.
* Wenn die bereitgestellte Kapazität für ein Cloud Volumes ONTAP-System 500 gib überschreitet, konvertiert BlueXP das System in das Essentials-Paket.
+
Sobald ein System in das Essentials-Paket konvertiert wird, wird das verwendet <<Hinweise zum Laden,Mindestgebühr>> Gilt.

+
Alle anderen Systeme mit einer bereitgestellten Kapazität von weniger als 500 gib bleiben auf Freemium (sofern sie mit dem Freemium-Angebot bereitgestellt wurden).





==== Essentials

Sie können in verschiedenen Konfigurationen nach Kapazität bezahlen:

* Wählen Sie Ihre Cloud Volumes ONTAP Konfiguration:
+
** Ein Single Node oder HA-System
** Datei- und Block-Storage oder sekundäre Daten für die Disaster Recovery (DR)


* Fügen Sie die Cloud-Datenservices von NetApp zu zusätzlichen Kosten hinzu


Weitere Informationen finden Sie unter link:concept-licensing-charging.html["Mehr zu kapazitätsbasierten Lizenzen"].



==== Optimiert

Sie bezahlen für bereitgestellte Kapazität und I/O-Vorgänge separat.

* Cloud Volumes ONTAP Single Node oder HA
* Der Ladevorgang basiert auf zwei Kostenkomponenten: Speicher und Nutzung (I/O).
+
Es fallen keine I/O-Kosten für Datenreplizierung (SnapMirror), Backups (SnapVault) oder NDMP an.



ifdef::azure[]

* Verfügbar im Azure Marketplace als Pay-as-you-go-Angebot oder als Jahresvertrag


endif::azure[]

ifdef::gcp[]

* Verfügbar im Google Cloud Marketplace als Pay-as-you-go-Angebot oder als Jahresvertrag


endif::gcp[]

* Fügen Sie die Cloud-Datenservices von NetApp zu zusätzlichen Kosten hinzu




==== Professionell

Sie bezahlen nach Kapazität für jede Art von Cloud Volumes ONTAP-Konfiguration mit unbegrenzten Backups.

* Ermöglicht die Lizenzierung jeder Cloud Volumes ONTAP Konfiguration
+
Single Node oder HA, berechnet für primäre und sekundäre Volumes dieselbe Kapazität

* Umfasst unbegrenzte Volume-Backups mit BlueXP Backup und Recovery, aber nur für Cloud Volumes ONTAP Systeme, die das Professional Paket verwenden.
+

NOTE: Für BlueXP  Backup und Recovery ist ein Pay-as-you-go-Abonnement (PAYGO) erforderlich, für die Nutzung dieses Services sind jedoch keine Kosten anfallen. Weitere Informationen zum Einrichten der Lizenzierung für BlueXP  Backup und Recovery finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["Lizenzierung für Backup und Recovery von BlueXP einrichten"^].

* Fügen Sie die Cloud-Datenservices von NetApp zu zusätzlichen Kosten hinzu




=== Verfügbarkeit kapazitätsbasierter Lizenzen

Die Verfügbarkeit der PAYGO- und BYOL-Lizenzen für Cloud Volumes ONTAP Systeme erfordert die Inbetriebnahme des BlueXP  Connectors. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#impact-on-cloud-volumes-ontap["Erfahren Sie mehr über Steckverbinder"^].



=== Erste Schritte

Erste Schritte mit kapazitätsbasierter Lizenzierung:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Lizenzierung für Cloud Volumes ONTAP in AWS einrichten"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Lizenzierung für Cloud Volumes ONTAP in Azure einrichten"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Lizenzierung für Cloud Volumes ONTAP in Google Cloud einrichten"]


endif::gcp[]



== Keystone Abonnement

Dieser auf einem Abonnement basierende Pay-as-you-grow-Service bietet eine nahtlose Hybrid-Cloud-Lösung für all jene, die Betriebskosten von Anfang an oder im Leasing bevorzugen.

Die Abrechnung basiert auf der Größe der gebuchten Kapazität für ein oder mehrere Cloud Volumes ONTAP HA-Paare in Ihrer Keystone Subscription.

Die bereitgestellte Kapazität für jedes Volume wird aggregiert und regelmäßig mit der gebuchten Kapazität in Ihrem Keystone Abonnement verglichen. Etwaige Überkapazitäten werden als Burst-Kapazität in Ihrem Keystone Abonnement abgerechnet.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Erfahren Sie mehr über NetApp Keystone"^].



=== Unterstützte Konfigurationen

Keystone Abonnements werden von HA-Paaren unterstützt. Diese Lizenzoption wird derzeit bei Systemen mit einzelnen Nodes nicht unterstützt.



=== Kapazitätsgrenze

Jedes einzelne Cloud Volumes ONTAP System unterstützt Kapazitäten von bis zu 2 PiB über Festplatten und Tiering zu Objekt-Storage.



=== Erste Schritte

So starten Sie mit einem Keystone Abonnement:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Lizenzierung für Cloud Volumes ONTAP in AWS einrichten"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Lizenzierung für Cloud Volumes ONTAP in Azure einrichten"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Lizenzierung für Cloud Volumes ONTAP in Google Cloud einrichten"]


endif::gcp[]



== Node-basierte Lizenzierung

Bei der Node-basierten Lizenzierung handelt es sich um das Lizenzmodell der vorherigen Generation, mit dem Cloud Volumes ONTAP pro Node lizenziert werden können. Dieses Lizenzmodell ist für Neukunden nicht verfügbar. Das Laden durch Knoten wurde durch die oben beschriebenen Methoden zum Aufladen von Kapazität ersetzt.

NetApp plant das Ende der Verfügbarkeit (EOA) und den Support (EOS) für Node-basierte Lizenzen. Nach der EOA und EOS müssen Node-basierte Lizenzen in kapazitätsbasierte Lizenzen konvertiert werden.

Weitere Informationen finden Sie unter https://mysupport.netapp.com/info/communications/CPC-00589.html["Mitteilungen für Kunden: CPC-00589"^].



=== Ende der Verfügbarkeit von Node-basierten Lizenzen

Ab dem 11. November 2024 wurde die begrenzte Verfügbarkeit von Node-basierten Lizenzen eingestellt. Der Support für Node-basierte Lizenzierung endet am 31. Dezember 2024.

Falls Sie über einen gültigen Node-basierten Vertrag verfügen, der über das EOA-Datum hinausgeht, können Sie die Lizenz bis zum Ablauf des Vertrags weiter nutzen. Nach Ablauf des Vertrags ist eine Umstellung auf das kapazitätsbasierte Lizenzmodell erforderlich. Wenn Sie keinen langfristigen Vertrag für einen Cloud Volumes ONTAP-Knoten haben, ist es wichtig, Ihre Konvertierung vor dem EOS-Datum zu planen.

Weitere Informationen zu den einzelnen Lizenztypen und deren Auswirkungen auf den EOA finden Sie in dieser Tabelle:

[cols="2*"]
|===
| Lizenztyp | Auswirkung nach EOA 


 a| 
Gültige Node-basierte Lizenz, die über Bring-Your-Own-License (BYOL) erworben wird
 a| 
Die Lizenz bleibt bis zum Ablauf gültig. Vorhandene ungenutzte Node-basierte Lizenzen können zur Implementierung neuer Cloud Volumes ONTAP Systeme verwendet werden.



 a| 
Abgelaufene Node-basierte Lizenz, die über BYOL erworben wurde
 a| 
Sie sind nicht berechtigt, mit dieser Lizenz neue Cloud Volumes ONTAP-Systeme zu implementieren. Die bestehenden Systeme können zwar weiterhin funktionieren, aber nach dem EOS-Datum erhalten Sie keinerlei Support oder Updates für Ihre Systeme.



 a| 
Gültige Node-basierte Lizenz bei PAYGO-Abonnement
 a| 
Nach dem EOS-Datum wird der NetApp Support solange nicht mehr erhalten, bis Sie eine kapazitätsbasierte Lizenz verwenden.

|===
.Ausschlüsse
NetApp ist sich bewusst, dass in bestimmten Situationen eine besondere Berücksichtigung erforderlich ist. Eine OA- und EOS-Lizenzierung auf Node-Basis gilt in den folgenden Fällen nicht:

* Kunden des öffentlichen Sektors in den USA
* Bereitstellungen im privaten Modus
* China-Region Bereitstellung von Cloud Volumes ONTAP in AWS


Für diese speziellen Szenarien bietet NetApp Unterstützung bei der Erfüllung der spezifischen Lizenzierungsanforderungen in Übereinstimmung mit vertraglichen Verpflichtungen und betrieblichen Anforderungen.


NOTE: Selbst in diesen Szenarien sind neue Node-basierte Lizenzen und Lizenzerneuerungen maximal ein Jahr ab dem Datum der Genehmigung gültig.



== Lizenzkonvertierung

BlueXP  ermöglicht eine nahtlose Konvertierung Node-basierter Lizenzen in Kapazitätskapazität basierend auf dem Lizenzkonvertierungstool. Informationen zum EOA für Node-basierte Lizenzierung finden Sie unter link:concept-licensing.html#end-of-availability-of-node-based-licenses["Ende der Verfügbarkeit von Node-basierten Lizenzen"].

Vor dem Übergang sollten Sie sich mit dem Unterschied zwischen den beiden Lizenzmodellen vertraut machen. Die Node-basierte Lizenzierung umfasst feste Kapazität für jede ONTAP Instanz, wodurch sich die Flexibilität einschränken lässt. Kapazitätsbasierte Lizenzierung hingegen ermöglicht einen gemeinsamen Storage-Pool über mehrere Instanzen hinweg. Dies erhöht die Flexibilität, optimiert die Ressourcenauslastung und verringert das Risiko von finanziellen Einbußen bei der Umverteilung von Workloads. Kapazitätsbasierte Ladefunktion passt sich nahtlos an sich verändernde Speicheranforderungen an.

Informationen dazu, wie Sie diese Konvertierung durchführen können, finden Sie unter link:task-convert-node-capacity.html["Konvertieren Sie Node-basierte Lizenzen in kapazitätsbasierte Lizenzen"].


NOTE: Die Konvertierung eines Systems von kapazitätsbasierter in Node-basierte Lizenzierung wird nicht unterstützt.
