---
sidebar: sidebar 
permalink: concept-active-iq.html 
keywords: autosupport, digital advisor, active iq digital advisor, telemetry 
summary: Die AutoSupport-Komponente von ONTAP erfasst Telemetrie und sendet diese zur Analyse. Digital Advisor analysiert die Daten von AutoSupport und bietet proaktive Betreuung und Optimierung. Mithilfe von künstlicher Intelligenz kann Digital Advisor potenzielle Probleme identifizieren und lösen, bevor sie sich auf Ihr Unternehmen auswirken. 
---
= AutoSupport und Digital Advisor werden für Cloud Volumes ONTAP eingesetzt
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die AutoSupport-Komponente von ONTAP erfasst Telemetrie und sendet diese zur Analyse. Digitaler Berater von Active IQ (auch bekannt als digitaler Berater) analysiert die Daten von AutoSupport und bietet proaktive Betreuung und Optimierung. Mithilfe von künstlicher Intelligenz kann Digital Advisor potenzielle Probleme identifizieren und lösen, bevor sie sich auf Ihr Unternehmen auswirken.

Mit Digital Advisor optimieren Sie Ihre Dateninfrastruktur in der gesamten globalen Hybrid Cloud. Dazu bieten wir Ihnen konkrete prädiktive Analysen und proaktiven Support über ein Cloud-basiertes Portal und mobile App. Mit einem aktiven SupportEdge-Vertrag stehen allen NetApp Kunden mit Daten-fokussierten Einblicken und Empfehlungen von Digital Advisor zur Verfügung (Funktionen variieren je nach Produkt und Support-Stufe).

Hier einige Dinge, die Sie mit Digital Advisor tun können:

* Planung von Upgrades:
+
Digital Advisor erkennt Probleme in Ihrer Umgebung, die durch ein Upgrade auf eine neuere Version von ONTAP behoben werden können. Die Komponente Upgrade Advisor unterstützt Sie bei der Planung eines erfolgreichen Upgrades.

* Sehen Sie sich das Wellness-System an.
+
Ihr Digital Advisor Dashboard meldet alle Probleme mit dem Wellness-Center und hilft Ihnen bei der Behebung dieser Probleme. Überwachen Sie die Systemkapazität, um sicherzugehen, dass nie mehr Speicherplatz belegt wird. Zeigen Sie Support-Cases für Ihr System an.

* Performance-Management:
+
Digital Advisor zeigt die Systemperformance über einen längeren Zeitraum an, als im ONTAP System Manager zu sehen ist. Identifizieren Sie Konfigurations- und Systemprobleme, die Ihre Performance beeinträchtigen.
Maximale Effizienz Anzeige von Storage-Effizienz-Metriken und Identifizierung von Möglichkeiten, mehr Daten auf weniger Speicherplatz zu speichern

* Anzeige von Inventar und Konfiguration
+
Digital Advisor zeigt den gesamten Bestand sowie Informationen zur Software- und Hardwarekonfiguration an. Prüfen Sie, wann die Serviceverträge ablaufen und verlängern Sie sie, um sicherzustellen, dass der Support weiterhin gewährleistet ist.



.Weiterführende Links
* https://docs.netapp.com/us-en/active-iq/["NetApp Dokumentation: Digitaler Berater"^]
* https://aiq.netapp.com/custom-dashboard/search["Starten Sie Digital Advisor"^]
* https://www.netapp.com/us/services/support-edge.aspx["SupportEdge Services"^]

