---
sidebar: sidebar 
permalink: concept-performance.html 
keywords: performance, technical report, TR, workload, cpu 
summary: Sie können die Performance-Ergebnisse überprüfen, um zu entscheiden, welche Workloads für Cloud Volumes ONTAP geeignet sind. 
---
= Leistung
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Performance-Ergebnisse überprüfen, um zu entscheiden, welche Workloads für Cloud Volumes ONTAP geeignet sind.



== Technische Berichte zur Performance

ifdef::aws[]

* Cloud Volumes ONTAP für AWS
+
https://["NetApp Technical Report 4383: Performance Characterization of Cloud Volumes ONTAP in Amazon Web Services with Application Workloads"^]



endif::aws[]

ifdef::azure[]

* Cloud Volumes ONTAP für Microsoft Azure
+
https://["Technischer Bericht von NetApp 4671: Performance-Charakterisierung von Cloud Volumes ONTAP in Azure mit Applikations-Workloads"^]



endif::azure[]

ifdef::gcp[]

* Cloud Volumes ONTAP für Google Cloud
+
https://["Technischer Bericht 4816: Performance-Merkmale von Cloud Volumes ONTAP für Google Cloud"^]



endif::gcp[]



== CPU-Performance

Cloud Volumes ONTAP-Nodes weisen eine hohe Auslastung (über 90 %) von den Monitoring-Tools Ihres Cloud-Providers auf. Dies liegt daran, dass ONTAP alle vCPUs, die der Virtual Machine zur Verfügung gestellt werden, so dass sie nach Bedarf verfügbar sind.

Hilfe finden Sie im https://["NetApp Knowledgebase Artikel dazu, wie die ONTAP-CPU-Auslastung mit der CLI überwacht wird"^]
