---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 'Sie können WORM-Storage (Write Once, Read Many) auf einem Cloud Volumes ONTAP System aktivieren, um Dateien für einen bestimmten Aufbewahrungszeitraum in unveränderter Form aufzubewahren. Cloud-WORM-Storage wird durch SnapLock Technologie unterstützt, d. h., WORM-Dateien sind auf Dateiebene gesichert.' 
---
= WORM-Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können WORM-Storage (Write Once, Read Many) auf einem Cloud Volumes ONTAP System aktivieren, um Dateien für einen bestimmten Aufbewahrungszeitraum in unveränderter Form aufzubewahren. Cloud-WORM-Storage wird durch SnapLock Technologie unterstützt, d. h., WORM-Dateien sind auf Dateiebene gesichert.

Die WORM-Funktion kann ohne zusätzliche Kosten mit Bring-Your-Own-License (BYOL) und Marketplace-Abonnements für Ihre Lizenzen genutzt werden. Wenden Sie sich an Ihren NetApp Vertriebsmitarbeiter, um WORM zu Ihrer aktuellen Lizenz hinzuzufügen.



== Funktionsweise VON WORM-Speicher

Sobald eine Datei im WORM-Storage gespeichert wurde, kann sie nicht mehr verändert werden, selbst wenn der Aufbewahrungszeitraum abgelaufen ist. Eine manipulationssichere Uhr bestimmt, wann die Aufbewahrungsfrist für eine WORM-Datei abgelaufen ist.

Nach Ablauf der Aufbewahrungsfrist sind Sie dafür verantwortlich, alle Dateien zu löschen, die Sie nicht mehr benötigen.



== WORM-Storage wird aktiviert

Wie Sie WORM-Speicher aktivieren, hängt von der verwendeten Cloud Volumes ONTAP Version ab.



=== Version 9.10.1 und höher

Ab Cloud Volumes ONTAP 9.10.1 haben Sie die Möglichkeit, WORM auf Volume-Ebene zu aktivieren oder zu deaktivieren.

Wenn Sie eine neue Cloud Volumes ONTAP Arbeitsumgebung erstellen, werden Sie aufgefordert, WORM-Speicher zu aktivieren oder zu deaktivieren:

* Wenn Sie WORM-Speicher beim Erstellen einer Arbeitsumgebung aktivieren, ist für jedes mit BlueXP erstellte Volume WORM aktiviert. Aber Sie können ONTAP System Manager oder die ONTAP CLI verwenden, um Volumes zu erstellen, auf denen WORM deaktiviert ist.
* Wenn Sie WORM-Storage beim Erstellen einer Arbeitsumgebung deaktivieren, ist jeder von Ihnen über BlueXP , ONTAP System Manager oder ONTAP erstellte Volume WORM deaktiviert.




=== Version 9.10.0 und früher

Sie können WORM Storage auf einem Cloud Volumes ONTAP System aktivieren, wenn Sie eine neue Arbeitsumgebung erstellen. Jedes von Ihnen aus BlueXP erstellte Volume ist DURCH WORM aktiviert. WORM Storage kann nicht auf einzelnen Volumes deaktiviert werden.



== Dateien werden in WORM gespeichert

Sie können eine Applikation verwenden, um Dateien über NFS oder CIFS in WORM zu übergeben, oder die ONTAP CLI verwenden, um Dateien automatisch in WORM zu übertragen. Sie können auch eine WORM-Datei verwenden, die Daten speichert, die inkrementell geschrieben werden, z. B. Protokollinformationen.

Nachdem Sie WORM Storage auf einem Cloud Volumes ONTAP System aktiviert haben, müssen Sie die ONTAP CLI für das gesamte Management von WORM Storage verwenden. Anweisungen finden Sie unter http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["ONTAP-Dokumentation"^].



== Aktivierung von WORM in einer Cloud Volumes ONTAP Arbeitsumgebung

Sie können WORM Storage beim Erstellen einer Cloud Volumes ONTAP-Arbeitsumgebung auf BlueXP  aktivieren. Sie können WORM auch in einer Arbeitsumgebung aktivieren, wenn WORM während der Erstellung nicht aktiviert ist. Nachdem Sie sie aktiviert haben, können Sie WORM nicht deaktivieren.

.Über diese Aufgabe
* WORM wird von ONTAP 9.10.1 und höher unterstützt.
* WORM mit Backup wird auf ONTAP 9.11.1 und höher unterstützt.


.Schritte
. Doppelklicken Sie auf der Seite Arbeitsfläche auf den Namen der Arbeitsumgebung, für die Sie WORM aktivieren möchten.
. Klicken Sie auf der Registerkarte Übersicht auf das Bedienfeld Funktionen und dann auf das Bleistiftsymbol neben *WORM*.
+
Wenn WORM bereits auf dem System aktiviert ist, ist das Bleistiftsymbol deaktiviert.

. Legen Sie auf der Seite *WORM* die Aufbewahrungsfrist für die Cluster-Compliance-Uhr fest.
+
Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["ONTAP-Dokumentation: Initialisieren Sie die Compliance-Uhr"^].

. Klicken Sie Auf *Set*.


.Nachdem Sie fertig sind
Sie können den Status von *WORM* im Funktionsbereich überprüfen. Nach der Aktivierung von WORM wird die SnapLock-Lizenz automatisch auf dem Cluster installiert. Sie können die SnapLock-Lizenz im ONTAP System Manager anzeigen.



== WORM-Dateien werden gelöscht

MIT der Funktion Privileged delete können SIE WORM-Dateien während des Aufbewahrungszeitraums löschen.

Anweisungen hierzu finden Sie unter https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["ONTAP-Dokumentation"^].



== WORM- und Daten-Tiering

Wenn Sie ein neues Cloud Volumes ONTAP 9.8 System oder höher erstellen, können Sie sowohl Daten-Tiering als AUCH WORM Storage gemeinsam aktivieren. Wenn Sie Daten-Tiering mit WORM-Storage aktivieren, können Sie die Daten auf einen Objektspeicher in der Cloud verschieben.

Sie sollten Folgendes über die Aktivierung von Daten-Tiering und WORM-Storage wissen:

* Daten, die auf Objekt-Storage verschoben werden, enthalten nicht die ONTAP WORM-Funktion. Um die End-to-End-WORM-Fähigkeit sicherzustellen, müssen Sie die Bucket-Berechtigungen korrekt einrichten.
* Die auf Objekt-Storage abgelegten Daten verfügen nicht über DIE WORM-Funktionalität, d. h., jeder mit vollem Zugriff auf Buckets und Container kann die durch ONTAP abgestuften Objekte löschen.
* Ein Wechsel- oder Downgrade auf Cloud Volumes ONTAP 9.8 ist nach Aktivierung VON WORM und Tiering gesperrt.




== Einschränkungen

* WORM Storage in Cloud Volumes ONTAP wird als „vertrauenswürdiger Storage-Administrator“ eingesetzt. WORM-Dateien sind vor Änderungen oder Änderungen geschützt, aber können von einem Cluster-Administrator gelöscht werden, selbst wenn diese Volumes nicht ABGELAUFENE WORM-Daten enthalten.
* Neben dem Modell eines vertrauenswürdigen Storage-Administrators arbeitet WORM Storage in Cloud Volumes ONTAP auch implizit unter einem Modell eines „vertrauenswürdigen Cloud-Administrators“. Ein Cloud-Administrator kann WORM-Daten vor ihrem Ablaufdatum löschen, indem er Cloud-Storage direkt vom Cloud-Provider entfernt oder bearbeitet.


.Verwandter Link
* link:reference-worm-snaplock.html["Erstellen Sie manipulationssichere Snapshot Kopien für WORM Storage"]

