---
sidebar: sidebar 
permalink: reference-networking-azure.html 
keywords: networking, network, requirements, connection, connections, vnet, security group, security groups, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, outbound, ports, blob, service endpoint 
summary: Richten Sie Ihr Azure Netzwerk ein, um Cloud Volumes ONTAP Systeme ordnungsgemäß funktionieren zu können. 
---
= Azure Networking für Cloud Volumes ONTAP einrichten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Richten Sie Ihr Azure Netzwerk ein, um Cloud Volumes ONTAP Systeme ordnungsgemäß funktionieren zu können.



== Anforderungen für Cloud Volumes ONTAP

Die folgenden Netzwerkanforderungen müssen in Azure erfüllt werden.



=== Outbound-Internetzugang

Cloud Volumes ONTAP-Systeme benötigen ausgehenden Internetzugang, um auf externe Endpunkte für verschiedene Funktionen zugreifen zu können. Cloud Volumes ONTAP kann nicht ordnungsgemäß funktionieren, wenn diese Endpunkte in Umgebungen mit strengen Sicherheitsanforderungen blockiert sind.

Der BlueXP -Connector kontaktiert auch mehrere Endpunkte für den täglichen Betrieb sowie die webbasierte Konsole BlueXP . Informationen zu den BlueXP -Endpunkten finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html#step-3-set-up-networking["Vom Connector aus kontaktierte Endpunkte anzeigen"^] und https://docs.netapp.com/us-en/bluexp-setup-admin/reference-networking-saas-console.html["Networking zur Nutzung der BlueXP Konsole vorbereiten"^].



==== Cloud Volumes ONTAP Endpunkte

Cloud Volumes ONTAP nutzt diese Endpunkte zur Kommunikation mit verschiedenen Services.

[cols="5*"]
|===
| Endpunkte | Anwendbar für | Zweck | BlueXP Implementierungsmodi | Auswirkung, falls nicht verfügbar 


| \https://netapp-cloud-account.auth0.com | Authentifizierung  a| 
Wird für die BlueXP -Authentifizierung verwendet.
| Standardmodi und eingeschränkte Modi.  a| 
Die Benutzerauthentifizierung schlägt fehl, und die folgenden Dienste sind weiterhin nicht verfügbar:

* Cloud Volumes ONTAP Services
* ONTAP-Dienste
* Protokolle und Proxy-Services




| https://vault.azure.net[] | Schlüsselspeicher | Dient zum Abrufen von geheimen Client-Schlüsseln aus dem Azure Key Vault bei Verwendung von vom Kunden gemanagten Schlüsseln (CMK). | Standardmodus, eingeschränkter und privater Modus. | Die Cloud Volumes ONTAP-Services sind nicht verfügbar. 


| \https://cloudmanager.cloud.netapp.com/tenancy | Mandantenfähigkeit | Wird verwendet, um die Cloud Volumes ONTAP-Ressourcen vom BlueXP -Mandanten abzurufen und Ressourcen und Benutzer zu autorisieren. | Standardmodi und eingeschränkte Modi. | Cloud Volumes ONTAP-Ressourcen und die Benutzer sind nicht autorisiert. 


| \https://support.NetApp.com/aods/asupmessage \https://support.NetApp.com/asupprod/post/1.0/postAsup | AutoSupport | Zum Senden von AutoSupport Telemetriedaten an den NetApp Support | Standardmodi und eingeschränkte Modi. | Informationen zu AutoSupport bleiben unzugestellt. 


| \https://management.azure.com \https://login.microsoftonline.com \https://blob.core.windows.net \https://core.windows.net | Öffentlichen Regionen | Kommunikation mit Azure-Services. | Standardmodus, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Service kommunizieren, um bestimmte BlueXP -Vorgänge in Azure auszuführen. 


| \https://management.chinacloudapi.cn \https://login.chinacloudapi.cn \https://blob.core.chinacloudapi.cn \https://core.chinacloudapi.cn | China-Region | Kommunikation mit Azure-Services. | Standardmodus, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Service kommunizieren, um bestimmte BlueXP -Vorgänge in Azure auszuführen. 


| \https://management.microsoftazure.de \https://login.microsoftonline.de \https://blob.core.cloudapi.de \https://core.cloudapi.de | Deutschland Region | Kommunikation mit Azure-Services. | Standardmodus, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Service kommunizieren, um bestimmte BlueXP -Vorgänge in Azure auszuführen. 


| \https://management.usgovcloudapi.net \https://login.microsoftonline.us \https://blob.core.usgovcloudapi.net \https://core.usgovcloudapi.net | Regierungseinrichtungen | Kommunikation mit Azure-Services. | Standardmodus, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Service kommunizieren, um bestimmte BlueXP -Vorgänge in Azure auszuführen. 


| \https://management.azure.microsoft.scloud \https://login.microsoftonline.microsoft.scloud \https://blob.core.microsoft.scloud \https://core.microsoft.scloud | Regionen des Verteidigungsministeriums der Regierung | Kommunikation mit Azure-Services. | Standardmodus, eingeschränkter und privater Modus. | Cloud Volumes ONTAP kann nicht mit dem Azure-Service kommunizieren, um bestimmte BlueXP -Vorgänge in Azure auszuführen. 
|===


=== Netzwerkkonfigurationen zur Unterstützung des Connector-Proxys

Sie können die für den BlueXP Connector konfigurierten Proxyserver verwenden, um ausgehenden Internetzugriff von Cloud Volumes ONTAP zu ermöglichen. BlueXP unterstützt zwei Proxy-Typen:

* *Expliziter Proxy*: Der ausgehende Datenverkehr von Cloud Volumes ONTAP verwendet die HTTP-Adresse des Proxyservers, der bei der Connector-Proxy-Konfiguration angegeben wurde. Der Connector-Administrator hat möglicherweise auch Benutzeranmeldeinformationen und Root-CA-Zertifikate für zusätzliche Authentifizierung konfiguriert. Wenn ein Root-CA-Zertifikat für den expliziten Proxy verfügbar ist, stellen Sie sicher, dass Sie dasselbe Zertifikat abrufen und in Ihre Cloud Volumes ONTAP Arbeitsumgebung hochladen. Verwenden Sie dazu  https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["ONTAP CLI: Sicherheitszertifikat installieren"^] Befehl.
* *Transparenter Proxy*: Das Netzwerk ist so konfiguriert, dass ausgehender Datenverkehr von Cloud Volumes ONTAP automatisch über den Connector-Proxy geleitet wird. Beim Einrichten eines transparenten Proxys muss der Connector-Administrator lediglich ein Root-CA-Zertifikat für die Konnektivität von Cloud Volumes ONTAP angeben, nicht die HTTP-Adresse des Proxy-Servers. Stellen Sie sicher, dass Sie dasselbe Root-CA-Zertifikat abrufen und in Ihre Cloud Volumes ONTAP Arbeitsumgebung hochladen. Verwenden Sie dazu  https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["ONTAP CLI: Sicherheitszertifikat installieren"^] Befehl.


Informationen zum Konfigurieren von Proxy-Servern für den BlueXP Connector finden Sie im  https://docs.netapp.com/us-en/bluexp-setup-admin/task-configuring-proxy.html["Konfigurieren Sie einen Konnektor für die Verwendung eines Proxy-Servers"^] .



=== IP-Adressen

BlueXP weist Cloud Volumes ONTAP in Azure automatisch die erforderliche Anzahl privater IP-Adressen zu. Sie müssen sicherstellen, dass Ihr Netzwerk über genügend private IP-Adressen verfügt.

Die Anzahl der LIFs, die BlueXP für Cloud Volumes ONTAP zuweist, hängt davon ab, ob Sie ein Single Node-System oder ein HA-Paar implementieren. Ein LIF ist eine IP-Adresse, die einem physischen Port zugewiesen ist. Für Managementtools wie SnapCenter ist eine SVM-Management-LIF erforderlich.


NOTE: Ein iSCSI LIF bietet Client-Zugriff über das iSCSI-Protokoll und wird vom System für andere wichtige Netzwerk-Workflows verwendet. Diese LIFs sind erforderlich und sollten nicht gelöscht werden.



==== IP-Adressen für ein Single Node-System

BlueXP weist 5 oder 6 IP-Adressen einem System mit einem Knoten zu:

* Cluster-Management-IP
* Node-Management-IP
* Intercluster IP für SnapMirror
* NFS/CIFS-IP
* ISCSI-IP
+

NOTE: Die iSCSI-IP ermöglicht den Client-Zugriff über das iSCSI-Protokoll. Es wird vom System auch für andere wichtige Netzwerk-Workflows verwendet. Dieses LIF ist erforderlich und sollte nicht gelöscht werden.

* SVM-Management (optional – nicht standardmäßig konfiguriert)




==== IP-Adressen für HA-Paare

BlueXP weist während der Bereitstellung 4 NICs (pro Node) IP-Adressen zu.

Beachten Sie, dass BlueXP in Azure eine SVM Management-LIF auf HA-Paaren erstellt, nicht jedoch auf Systemen mit einzelnen Nodes.

*NIC0*

* Node-Management-IP
* Intercluster-IP
* ISCSI-IP
+

NOTE: Die iSCSI-IP ermöglicht den Client-Zugriff über das iSCSI-Protokoll. Es wird vom System auch für andere wichtige Netzwerk-Workflows verwendet. Dieses LIF ist erforderlich und sollte nicht gelöscht werden.



*NIC1*

* Cluster-Netzwerk-IP


*NIC2*

* Cluster Interconnect IP (HA-IC)


*NIC3*

* PageBLOB NIC-IP (Festplattenzugriff)



NOTE: NIC3 gilt nur für HA-Implementierungen, die BLOB Storage auf Seite verwenden.

Die oben genannten IP-Adressen migrieren nicht bei Failover-Ereignissen.

Zusätzlich werden 4 Frontend-IPs (FIPS) für die Migration bei Failover-Ereignissen konfiguriert. Diese Frontend-IPs sind im Load Balancer aktiv.

* Cluster-Management-IP
* NodeA Daten-IP (NFS/CIFS)
* NodeB-Daten-IP (NFS/CIFS)
* SVM-Management-IP




=== Sichere Verbindung zu Azure Services

Standardmäßig aktiviert BlueXP einen Azure Private Link für Verbindungen zwischen Blob-Storage-Konten auf der Cloud Volumes ONTAP- und Azure-Seite.

In den meisten Fällen ist nichts für Sie erforderlich – BlueXP managt den Azure Private Link für Sie. Aber wenn Sie Azure Private DNS verwenden, dann müssen Sie eine Konfigurationsdatei bearbeiten. Sie sollten auch eine Anforderung für den Connector-Standort in Azure kennen.

Sie können die Private Link-Verbindung auch deaktivieren, wenn dies von Ihren geschäftlichen Anforderungen erforderlich ist. Wenn Sie den Link deaktivieren, konfiguriert BlueXP stattdessen Cloud Volumes ONTAP für die Verwendung eines Service-Endpunkts.

link:task-enabling-private-link.html["Weitere Informationen zur Verwendung von Azure Private Links oder Service-Endpunkten mit Cloud Volumes ONTAP"].



=== Verbindungen zu anderen ONTAP Systemen

Um Daten zwischen einem Cloud Volumes ONTAP System in Azure und ONTAP Systemen in anderen Netzwerken zu replizieren, benötigen Sie eine VPN-Verbindung zwischen dem Azure vnet und dem anderen Netzwerk, beispielsweise Ihrem Unternehmensnetzwerk.

Anweisungen finden Sie unter https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-site-to-site-resource-manager-portal["Microsoft Azure Dokumentation: Erstellen Sie eine Site-to-Site-Verbindung im Azure-Portal"^].



=== Port für den HA Interconnect

Ein Cloud Volumes ONTAP HA-Paar enthält einen HA Interconnect, der jedem Knoten erlaubt, kontinuierlich zu überprüfen, ob sein Partner funktioniert und um Protokolldaten für den anderen nichtflüchtigen Speicher zu spiegeln. Das HA Interconnect verwendet TCP Port 10006 für die Kommunikation.

Standardmäßig ist die Kommunikation zwischen den HA Interconnect LIFs offen, und es gibt keine Sicherheitsgruppenregeln für diesen Port. Wenn Sie jedoch eine Firewall zwischen den HA Interconnect LIFs erstellen, müssen Sie sicherstellen, dass TCP Traffic für Port 10006 offen ist, damit das HA-Paar ordnungsgemäß arbeiten kann.



=== Nur ein HA-Paar in einer Azure-Ressourcengruppe

Sie müssen für jedes Cloud Volumes ONTAP HA-Paar, das Sie in Azure implementieren, eine _dedizierte_ Ressourcengruppe verwenden. Es wird nur ein HA-Paar in einer Ressourcengruppe unterstützt.

Bei BlueXP treten Verbindungsprobleme auf, wenn Sie versuchen, ein zweites Cloud Volumes ONTAP HA-Paar in einer Azure Ressourcengruppe bereitzustellen.



=== Regeln für Sicherheitsgruppen

BlueXP erstellt Azure-Sicherheitsgruppen, die die eingehenden und ausgehenden Regeln für den erfolgreichen Betrieb von Cloud Volumes ONTAP enthalten.  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html["Zeigen Sie die Sicherheitsgruppenregeln für den Konnektor an"^] .

Die Azure-Sicherheitsgruppen für Cloud Volumes ONTAP erfordern, dass die entsprechenden Ports für die interne Kommunikation zwischen den Knoten geöffnet sind.  https://docs.netapp.com/us-en/ontap/networking/ontap_internal_ports.html["Informieren Sie sich über interne ONTAP Ports"^] .

Wir empfehlen, die vordefinierten Sicherheitsgruppen nicht zu ändern oder benutzerdefinierte Sicherheitsgruppen zu verwenden. Falls Sie dies dennoch tun müssen, beachten Sie, dass das Cloud Volumes ONTAP-System für den Bereitstellungsprozess vollen Zugriff innerhalb seines eigenen Subnetzes benötigt. Wenn Sie nach Abschluss der Bereitstellung die Netzwerksicherheitsgruppe ändern möchten, achten Sie darauf, dass die Cluster-Ports und HA-Netzwerk-Ports geöffnet bleiben. Dies gewährleistet eine reibungslose Kommunikation innerhalb des Cloud Volumes ONTAP-Clusters (Any-to-Any-Kommunikation zwischen den Knoten).



==== Eingehende Regeln für Single-Node-Systeme

Wenn Sie eine Arbeitsumgebung erstellen und eine vordefinierte Sicherheitsgruppe auswählen, können Sie den Datenverkehr innerhalb einer der folgenden Optionen zulassen:

* *Nur ausgewähltes vnet*: Die Quelle für eingehenden Datenverkehr ist der Subnetz-Bereich des vnet für das Cloud Volumes ONTAP-System und der Subnetz-Bereich des vnet, in dem sich der Connector befindet. Dies ist die empfohlene Option.
* *Alle VNets*: Die Quelle für eingehenden Datenverkehr ist der IP-Bereich 0.0.0.0/0.
* *Disabled*: Diese Option beschränkt den Zugriff auf das öffentliche Netzwerk auf Ihr Speicherkonto und deaktiviert das Daten-Tiering für Cloud Volumes ONTAP-Systeme. Dies ist eine empfohlene Option, wenn Ihre privaten IP-Adressen aufgrund von Sicherheitsvorschriften und -Richtlinien nicht innerhalb desselben vnet offengelegt werden sollten.


[cols="4*"]
|===
| Priorität und Name | Port und Protokoll | Quelle und Ziel | Beschreibung 


| 1000 Inbound_SSH | 22 TCP | Beliebige Art | SSH-Zugriff auf die IP-Adresse der Cluster Management LIF oder einer Node Management LIF 


| 1001 Inbound_http | 80 TCP | Beliebige Art | HTTP-Zugriff auf die Web-Konsole von ONTAP System Manager mithilfe der IP-Adresse der Cluster-Management-LIF 


| 1002 Inbound_111_tcp | 111 TCP | Beliebige Art | Remote-Prozeduraufruf für NFS 


| 1003 Inbound_111_udp | 111 UDP | Beliebige Art | Remote-Prozeduraufruf für NFS 


| 1004 eingehend_139 | 139 TCP | Beliebige Art | NetBIOS-Servicesitzung für CIFS 


| 1005 Inbound_161-162 _tcp | 161-162 TCP | Beliebige Art | Einfaches Netzwerkverwaltungsprotokoll 


| 1006 Inbound_161-162 _udp | 161-162 UDP | Beliebige Art | Einfaches Netzwerkverwaltungsprotokoll 


| 1007 eingehend_443 | 443 TCP | Beliebige Art | Konnektivität mit dem Connector und HTTPS-Zugriff auf die ONTAP System Manager Webkonsole mithilfe der IP-Adresse der Cluster-Management-LIF 


| 1008 eingehend_445 | 445 TCP | Beliebige Art | Microsoft SMB/CIFS über TCP mit NETBIOS-Framing 


| 1009 Inbound_635_tcp | 635 TCP | Beliebige Art | NFS-Mount 


| 1010 Inbound_635_udp | 635 UDP | Beliebige Art | NFS-Mount 


| 1011 eingehend_749 | 749 TCP | Beliebige Art | Kerberos 


| 1012 Inbound_2049_tcp | 2049 TCP | Beliebige Art | NFS-Server-Daemon 


| 1013 Inbound_2049_udp | 2049 UDP | Beliebige Art | NFS-Server-Daemon 


| 1014 eingehend_3260 | 3260 TCP | Beliebige Art | ISCSI-Zugriff über die iSCSI-Daten-LIF 


| 1015 Inbound_4045-4046_tcp | 4045-4046 TCP | Beliebige Art | NFS Lock Daemon und Network Status Monitor 


| 1016 Inbound_4045-4046_udp | 4045-4046 UDP | Beliebige Art | NFS Lock Daemon und Network Status Monitor 


| 1017 eingehend_10000 | 10000 TCP | Beliebige Art | Backup mit NDMP 


| 1018 eingehend_11104-11105 | 11104-11105 TCP | Beliebige Art | SnapMirror Datenübertragung 


| 3000 Inbound_Deny_all_tcp | Alle TCP-Ports | Beliebige Art | Blockieren Sie den gesamten anderen TCP-eingehenden Datenverkehr 


| 3001 Inbound_Deny_all_udp | Alle Ports UDP | Beliebige Art | Alle anderen UDP-eingehenden Datenverkehr blockieren 


| 65000 AllowVnetInBound | Alle Ports und Protokolle | VirtualNetwork zu VirtualNetwork | Eingehender Verkehr aus dem vnet 


| 65001 AllowAzureLoad BalancerInBound | Alle Ports und Protokolle | AzureLoadBalancer zu jedem | Datenverkehr vom Azure Standard Load Balancer 


| 65500 DenyAllInBound | Alle Ports und Protokolle | Beliebige Art | Alle anderen eingehenden Datenverkehr blockieren 
|===


==== Eingehende Regeln für HA-Systeme

Wenn Sie eine Arbeitsumgebung erstellen und eine vordefinierte Sicherheitsgruppe auswählen, können Sie den Datenverkehr innerhalb einer der folgenden Optionen zulassen:

* *Nur ausgewähltes vnet*: Die Quelle für eingehenden Datenverkehr ist der Subnetz-Bereich des vnet für das Cloud Volumes ONTAP-System und der Subnetz-Bereich des vnet, in dem sich der Connector befindet. Dies ist die empfohlene Option.
* *Alle VNets*: Die Quelle für eingehenden Datenverkehr ist der IP-Bereich 0.0.0.0/0.



NOTE: HA-Systeme weisen weniger eingehende Regeln als Systeme mit einzelnen Nodes auf, da eingehender Datenverkehr durch den Azure Standard Load Balancer geleitet wird. Aus diesem Grund sollte der Verkehr aus dem Load Balancer geöffnet sein, wie in der Regel "AllowAzureLoadBalancerInBound" gezeigt.

* *Disabled*: Diese Option beschränkt den Zugriff auf das öffentliche Netzwerk auf Ihr Speicherkonto und deaktiviert das Daten-Tiering für Cloud Volumes ONTAP-Systeme. Dies ist eine empfohlene Option, wenn Ihre privaten IP-Adressen aufgrund von Sicherheitsvorschriften und -Richtlinien nicht innerhalb desselben vnet offengelegt werden sollten.


[cols="4*"]
|===
| Priorität und Name | Port und Protokoll | Quelle und Ziel | Beschreibung 


| 100 eingehend_443 | 443 beliebiges Protokoll | Beliebige Art | Konnektivität mit dem Connector und HTTPS-Zugriff auf die ONTAP System Manager Webkonsole mithilfe der IP-Adresse der Cluster-Management-LIF 


| 101 Inbound_111_tcp | 111 beliebiges Protokoll | Beliebige Art | Remote-Prozeduraufruf für NFS 


| 102 Inbound_2049_tcp | 2049 beliebiges Protokoll | Beliebige Art | NFS-Server-Daemon 


| 111 Inbound_SSH | 22 beliebiges Protokoll | Beliebige Art | SSH-Zugriff auf die IP-Adresse der Cluster Management LIF oder einer Node Management LIF 


| 121 eingehend_53 | 53 beliebiges Protokoll | Beliebige Art | DNS und CIFS 


| 65000 AllowVnetInBound | Alle Ports und Protokolle | VirtualNetwork zu VirtualNetwork | Eingehender Verkehr aus dem vnet 


| 65001 AllowAzureLoad BalancerInBound | Alle Ports und Protokolle | AzureLoadBalancer zu jedem | Datenverkehr vom Azure Standard Load Balancer 


| 65500 DenyAllInBound | Alle Ports und Protokolle | Beliebige Art | Alle anderen eingehenden Datenverkehr blockieren 
|===


==== Regeln für ausgehende Anrufe

Die vordefinierte Sicherheitsgruppe für Cloud Volumes ONTAP öffnet den gesamten ausgehenden Datenverkehr. Wenn dies akzeptabel ist, befolgen Sie die grundlegenden Regeln für ausgehende Anrufe. Wenn Sie strengere Regeln benötigen, verwenden Sie die erweiterten Outbound-Regeln.



===== Grundlegende Regeln für ausgehende Anrufe

Die vordefinierte Sicherheitsgruppe für Cloud Volumes ONTAP enthält die folgenden ausgehenden Regeln.

[cols="3*"]
|===
| Port | Protokoll | Zweck 


| Alle | Alle TCP | Gesamter abgehender Datenverkehr 


| Alle | Alle UDP-Protokolle | Gesamter abgehender Datenverkehr 
|===


===== Erweiterte Outbound-Regeln

Wenn Sie strenge Regeln für ausgehenden Datenverkehr benötigen, können Sie mit den folgenden Informationen nur die Ports öffnen, die für die ausgehende Kommunikation durch Cloud Volumes ONTAP erforderlich sind.


NOTE: Die Quelle ist die Schnittstelle (IP-Adresse) auf dem Cloud Volumes ONTAP System.

[cols="10,10,6,20,20,34"]
|===
| Service | Port | Protokoll | Quelle | Ziel | Zweck 


.18+| Active Directory | 88 | TCP | Node Management-LIF | Active Directory-Gesamtstruktur | Kerberos V-Authentifizierung 


| 137 | UDP | Node Management-LIF | Active Directory-Gesamtstruktur | NetBIOS-Namensdienst 


| 138 | UDP | Node Management-LIF | Active Directory-Gesamtstruktur | Netbios Datagramm-Dienst 


| 139 | TCP | Node Management-LIF | Active Directory-Gesamtstruktur | Sitzung für den NETBIOS-Dienst 


| 389 | TCP UND UDP | Node Management-LIF | Active Directory-Gesamtstruktur | LDAP 


| 445 | TCP | Node Management-LIF | Active Directory-Gesamtstruktur | Microsoft SMB/CIFS über TCP mit NETBIOS-Framing 


| 464 | TCP | Node Management-LIF | Active Directory-Gesamtstruktur | Kerberos V Passwort ändern und festlegen (SET_CHANGE) 


| 464 | UDP | Node Management-LIF | Active Directory-Gesamtstruktur | Kerberos-Schlüsselverwaltung 


| 749 | TCP | Node Management-LIF | Active Directory-Gesamtstruktur | Kerberos V - Kennwort ändern und festlegen (RPCSEC_GSS) 


| 88 | TCP | Daten-LIF (NFS, CIFS, iSCSI) | Active Directory-Gesamtstruktur | Kerberos V-Authentifizierung 


| 137 | UDP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | NetBIOS-Namensdienst 


| 138 | UDP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Netbios Datagramm-Dienst 


| 139 | TCP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Sitzung für den NETBIOS-Dienst 


| 389 | TCP UND UDP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | LDAP 


| 445 | TCP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Microsoft SMB/CIFS über TCP mit NETBIOS-Framing 


| 464 | TCP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Kerberos V Passwort ändern und festlegen (SET_CHANGE) 


| 464 | UDP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Kerberos-Schlüsselverwaltung 


| 749 | TCP | Data LIF (NFS, CIFS) | Active Directory-Gesamtstruktur | Kerberos V - Passwort ändern und festlegen (RPCSEC_GSS) 


.3+| AutoSupport | HTTPS | 443 | Node Management-LIF | support.netapp.com | AutoSupport (HTTPS ist der Standard) 


| HTTP | 80 | Node Management-LIF | support.netapp.com | AutoSupport (nur wenn das Transportprotokoll von HTTPS zu HTTP geändert wird) 


| TCP | 3128 | Node Management-LIF | Stecker | Senden von AutoSupport-Nachrichten über einen Proxy-Server auf dem Connector, falls keine ausgehende Internetverbindung verfügbar ist 


| Konfigurations-Backups | HTTP | 80 | Node Management-LIF | \Http://<connector-IP-address>/occm/offboxconfig | Senden Sie Konfigurationssicherungen an den Connector. link:https://docs.netapp.com/us-en/ontap/system-admin/node-cluster-config-backed-up-automatically-concept.html["ONTAP-Dokumentation"^]. 


| DHCP | 68 | UDP | Node Management-LIF | DHCP | DHCP-Client für die erstmalige Einrichtung 


| DHCPS | 67 | UDP | Node Management-LIF | DHCP | DHCP-Server 


| DNS | 53 | UDP | Node Management LIF und Daten LIF (NFS, CIFS) | DNS | DNS 


| NDMP | 18600-18699 | TCP | Node Management-LIF | Zielserver | NDMP-Kopie 


| SMTP | 25 | TCP | Node Management-LIF | Mailserver | SMTP-Warnungen können für AutoSupport verwendet werden 


.4+| SNMP | 161 | TCP | Node Management-LIF | Server überwachen | Überwachung durch SNMP-Traps 


| 161 | UDP | Node Management-LIF | Server überwachen | Überwachung durch SNMP-Traps 


| 162 | TCP | Node Management-LIF | Server überwachen | Überwachung durch SNMP-Traps 


| 162 | UDP | Node Management-LIF | Server überwachen | Überwachung durch SNMP-Traps 


.2+| SnapMirror | 11104 | TCP | Intercluster-LIF | ONTAP Intercluster-LIFs | Management von interclusterübergreifenden Kommunikationssitzungen für SnapMirror 


| 11105 | TCP | Intercluster-LIF | ONTAP Intercluster-LIFs | SnapMirror Datenübertragung 


| Syslog | 514 | UDP | Node Management-LIF | Syslog-Server | Syslog-Weiterleitungsmeldungen 
|===


== Anforderungen an den Steckverbinder

Wenn Sie noch keinen Connector erstellt haben, sollten Sie auch die Netzwerkanforderungen für den Connector prüfen.

* https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-azure.html["Zeigen Sie die Netzwerkanforderungen für den Connector an"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-ports-azure.html["Für Sicherheitsgruppen gibt es in Azure Regeln"^]


.Verwandte Themen
* link:task-verify-autosupport.html["Überprüfen Sie die AutoSupport-Einrichtung für Cloud Volumes ONTAP"]
* https://docs.netapp.com/us-en/ontap/networking/ontap_internal_ports.html["Informieren Sie sich über interne ONTAP Ports"^].

