---
sidebar: sidebar 
permalink: task-managing-svms-gcp.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported, create svm, create storage vm, create vserver 
summary: Eine Storage VM ist eine Virtual Machine, die in ONTAP ausgeführt wird und Ihren Kunden Storage und Datenservices zur Verfügung stellt. Sie können dies als SVM oder vServer wissen. Cloud Volumes ONTAP ist standardmäßig mit einer Storage-VM konfiguriert, aber einige Konfigurationen unterstützen zusätzliche Storage-VMs. 
---
= Managen Sie die Datenservice-Storage-VMs für Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Eine Storage VM ist eine Virtual Machine, die in ONTAP ausgeführt wird und Ihren Kunden Storage und Datenservices zur Verfügung stellt. Vielleicht wissen Sie das als _SVM_ oder _vServer_. Cloud Volumes ONTAP ist standardmäßig mit einer Storage-VM konfiguriert, aber einige Konfigurationen unterstützen zusätzliche Storage-VMs.

Um zusätzliche Storage-VMs für Datenbereitstellung in Google Cloud zu erstellen und zu managen, sollten Sie die BlueXP -APIs verwenden. Das liegt daran, dass die APIs die Erstellung der Storage-VMs automatisieren und die erforderlichen Netzwerkschnittstellen konfigurieren. Beim Erstellen der Storage-VMs konfiguriert BlueXP  die erforderlichen LIF-Services sowie eine iSCSI LIF, die für ausgehende SMB/CIFS-Kommunikation von der Storage-VM benötigt wird.

Informationen zum Ausführen von Cloud Volumes ONTAP-API-Aufrufen finden Sie unter https://docs.netapp.com/us-en/bluexp-automation/cm/your_api_call.html#step-1-select-the-identifie["Ihr erster API-Aufruf"^].



== Unterstützte Anzahl von Storage-VMs

Ab Cloud Volumes ONTAP 9.11.1 werden basierend auf Ihrer Lizenz mehrere Storage VMs mit spezifischen Konfigurationen unterstützt. Überprüfen Sie im die https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/index.html["Versionshinweise zu Cloud Volumes ONTAP"^] unterstützte Anzahl von Storage-VMs für Ihre Version von Cloud Volumes ONTAP.

Alle Versionen von Cloud Volumes ONTAP vor Version 9.11.1 unterstützen nur eine Daten-Serving-VM und eine Ziel-Storage-VM, die für das Disaster Recovery verwendet wurde. Sie können die Ziel-Storage-VM für Datenzugriff aktivieren, wenn es einen Ausfall auf der Quell-Storage-VM gibt.



== Erstellen einer Storage-VM

Basierend auf Konfiguration und Lizenztyp können Sie mithilfe der BlueXP  APIs mehrere Storage VMs auf einem Single Node-System oder in einer HA-Konfiguration (High Availability, Hochverfügbarkeit) erstellen.

.Über diese Aufgabe
Wenn Sie Storage-VMs mit den APIs erstellen und die erforderlichen Netzwerkschnittstellen konfigurieren, ändert BlueXP  auch die `default-data-files` Richtlinien der Datenspeicher-VMs, indem die folgenden Services von der logischen Schnittstelle für NAS-Daten entfernt und zur iSCSI-Datenschnittstelle hinzugefügt werden, die für Outbound-Managementverbindungen verwendet wird:

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.Bevor Sie beginnen
Der Connector erfordert bestimmte Berechtigungen, um Storage-VMs für Cloud Volumes ONTAP HA-Paare zu erstellen. Die erforderlichen Berechtigungen sind in enthalten https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Die von NetApp bereitgestellten Richtlinien"^].



=== Single Node-System

Verwenden Sie den folgenden API-Aufruf, um eine Storage-VM auf einem System mit einem einzelnen Node zu erstellen.

`POST /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

Nehmen Sie die folgenden Parameter in den Anforderungstext auf:

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== HA-Paar

Verwenden Sie den folgenden API-Aufruf, um eine Storage-VM auf einem HA-Paar zu erstellen:

`POST /gcp/ha/working-environments/{workingEnvironmentId}/svm/`

Nehmen Sie die folgenden Parameter in den Anforderungstext auf:

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
}
----


== Management von Storage VMs

Mit den BlueXP  APIs können Sie Storage-VMs in einzelnen Node- und HA-Konfigurationen umbenennen und löschen.

.Bevor Sie beginnen
Der Connector erfordert bestimmte Berechtigungen für das Management von Storage-VMs für Cloud Volumes ONTAP HA-Paare. Die erforderlichen Berechtigungen sind in enthalten https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-gcp.html["Die von NetApp bereitgestellten Richtlinien"^].



=== Benennen Sie eine Storage-VM um

Um eine Storage-VM umzubenennen, sollten Sie die Namen der vorhandenen Storage-VM und der neuen Storage-VM als Parameter angeben.

.Schritte
* Verwenden Sie den folgenden API-Aufruf, um eine Storage-VM auf einem System mit einem einzelnen Node umzubenennen:
+
`PUT /gcp/vsa/working-environments/{workingEnvironmentId}/svm`

+
Nehmen Sie die folgenden Parameter in den Anforderungstext auf:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* Verwenden Sie den folgenden API-Aufruf, um eine Storage-VM auf einem HA-Paar umzubenennen:
+
`PUT /gcp/ha/working-environments/{workingEnvironmentId}/svm`

+
Nehmen Sie die folgenden Parameter in den Anforderungstext auf:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== Löschen einer Speicher-VM

Sie können in einem einzelnen Node oder einer HA-Konfiguration eine Storage-VM entfernen, wenn diese nicht über aktive Volumes verfügt.

.Schritte
* Verwenden Sie den folgenden API-Aufruf, um eine Storage-VM auf einem System mit einem einzelnen Node zu löschen:
+
`DELETE /gcp/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* Verwenden Sie den folgenden API-Aufruf, um eine Storage-VM auf einem HA-Paar zu löschen:
+
`DELETE /gcp/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`



.Verwandte Informationen
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Die Verwendung der API wird vorbereitet"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Cloud Volumes ONTAP Workflows"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["Abrufen der erforderlichen Kennungen"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["Verwenden Sie die BlueXP REST-APIs"^]

