---
sidebar: sidebar 
permalink: task-configure-placement-group-failure-aws.html 
keywords: placement group, failure, HA single zone, app.conf, rollback, AWS 
summary: Für Verbindungen zu den zugehörigen Storage-Konten nutzt Cloud Volumes ONTAP einen Azure Private Link. Bei Bedarf können Sie Azure Private Links deaktivieren und stattdessen Service-Endpunkte verwenden. 
---
= Erstellung von Platzierungsgruppen für Cloud Volumes ONTAP HA-Paare in AWS einzelnen AZS konfigurieren
:allow-uri-read: 


[role="lead"]
Bei Ausfall der Erstellung der Platzierungsgruppe können Cloud Volumes ONTAP-Implementierungen für Hochverfügbarkeit (High Availability, HA) in AWS Single Availability Zone (AZ) ausfallen und ein Rollback durchführen. Die Erstellung der Platzierungsgruppe schlägt ebenfalls fehl, und die Implementierung wird wieder ausgeführt, wenn der Cloud Volumes ONTAP-Node und die Mediatorinstanz nicht verfügbar sind. Um dies zu vermeiden, können Sie die Konfiguration so ändern, dass die Bereitstellung auch dann abgeschlossen werden kann, wenn die Erstellung der Platzierungsgruppe fehlschlägt.

Beim Umgehen des Rollback-Prozesses wird der Cloud Volumes ONTAP-Bereitstellungsprozess erfolgreich abgeschlossen und Sie werden benachrichtigt, dass die Erstellung der Platzierungsgruppe unvollständig ist.

.Schritte
. Verwenden Sie SSH, um eine Verbindung zum Connector-Host herzustellen und sich anzumelden.
. Navigieren Sie zu `/opt/application/netapp/cloudmanager/docker_occm/data`.
.  `app.conf`Ändern Sie den Wert des `rollback-on-placement-group-failure` Parameters in `false`. Der Standardwert dieses Parameters ist `true`.
+
[listing]
----
{
    "occm" : {
        "aws" : {
            "rollback-on-placement-group-failure" : false
        }
    }
}
----
. Speichern Sie die Datei und melden Sie sich vom Connector ab. Sie müssen den Connector nicht neu starten.

