---
sidebar: sidebar 
permalink: task-file-verification-mac.html 
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP, Cloud Volumes, CLI, Mac OS 
summary: Überprüfen Sie eine exportierte VHD-Dateisignatur über das Cloud Volumes ONTAP-Image-Digest-Dateiwerkzeug unter Mac OS 
---
= Überprüfen Sie die Signatur des Azure Marketplace-Images für Cloud Volumes ONTAP unter MAC OS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine exportierte VHD-Dateisignatur für Mac OS überprüfen, indem Sie die folgenden Schritte ausführen.

.Schritte
. Laden Sie die Datei Azure Image Digest von der herunter https://mysupport.netapp.com/site/["NetApp Support Website"^] Und extrahieren Sie die Digest-Datei(.SIG), die Zertifikatdatei des öffentlichen Schlüssels(.pem) und die Zertifikatdatei der Kette(.pem).
+
Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-download-digest-file.html["Azure Image Digest Datei herunterladen"^] Finden Sie weitere Informationen.

. Überprüfen Sie die Vertrauenskette.
+
[listing]
----
% openssl verify -CAfile Certificate-Chain-9.15.0P1_azure.pem Certificate-9.15.0P1_azure.pem
Certificate-9.15.0P1_azure.pem: OK
----
. Entfernen Sie die führende 1 MB (1048576 Byte) und die letzte 512 Byte VHD-Datei.
+
Wenn 'Tail' verwendet wird, gibt die Option '-c +K' Bytes beginnend mit den KTH Bytes aus
Der angegebenen Datei. Daher wird 1048577 an 'tail -c' übergeben. Es dauert ca. 13m
Damit der tail-Befehl unter Mac OS abgeschlossen wird.

+
[listing]
----
% tail -c +1048577 ./9150.01000024.05090105.vhd > ./sign.tmp.tail
% head -c -512 ./sign.tmp.tail > sign.tmp
% rm ./sign.tmp.tail
----
. Verwenden Sie openssl, um den öffentlichen Schlüssel aus dem Zertifikat zu extrahieren und den gestreiften Schlüssel zu überprüfen
Datei(sign.tmp) mit Signaturdatei und öffentlichem Schlüssel.
+
Wenn die Eingabedatei die Überprüfung besteht, wird im Befehl „Überprüfung OK“ angezeigt.
Andernfalls wird „Überprüfungsfehler“ angezeigt.

+
[listing]
----
% openssl x509 -pubkey -noout -in ./Certificate-9.15.0P1_azure.pem > ./Code-Sign-Cert-Public-key.pub

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verified OK

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----
. Den Arbeitsbereich bereinigen.
+
[listing]
----
% rm ./9150.01000024.05090105.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----

