---
sidebar: sidebar 
permalink: task-administer-advanced-view.html 
keywords: system manager, advanced view, access system manager, load system manager, use system manager, cloud tiering 
summary: Wenn Sie erweitertes Management von Cloud Volumes ONTAP durchführen möchten, können Sie dies mit ONTAP System Manager durchführen. Dabei handelt es sich um eine Managementoberfläche, die einem ONTAP System bereitgestellt wird. Die System Manager Schnittstelle ist direkt in BlueXP integriert, sodass Sie BlueXP nicht für erweitertes Management verlassen müssen. 
---
= Cloud Volumes ONTAP mit der erweiterten Ansicht verwalten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie erweitertes Management von Cloud Volumes ONTAP durchführen möchten, können Sie dies mit ONTAP System Manager durchführen. Dabei handelt es sich um eine Managementoberfläche, die einem ONTAP System bereitgestellt wird. Die System Manager Schnittstelle ist direkt in BlueXP integriert, sodass Sie BlueXP nicht für erweitertes Management verlassen müssen.



== Funktionen

Die erweiterte Ansicht in BlueXP bietet Ihnen zusätzliche Verwaltungsfunktionen:

* Erweitertes Storage-Management
+
Managen von Konsistenzgruppen, Shares, qtrees, Quotas und Storage-VMs

* Netzwerkmanagement
+
Managen Sie IPspaces, Netzwerkschnittstellen, Portsätze und ethernet-Ports.

* Ereignisse und Jobs
+
Anzeige von Ereignisprotokollen, Systemwarnungen, Jobs und Prüfprotokollen.

* Erweiterte Datensicherung
+
Sicherung von Storage VMs, LUNs und Konsistenzgruppen

* Host-Management
+
Richten Sie SAN-Initiatorgruppen und NFS-Clients ein.





== Unterstützte Konfigurationen

Das erweiterte Management über ONTAP System Manager wird von Cloud Volumes ONTAP 9.10.0 und höher in standardmäßigen Cloud-Regionen unterstützt.

Die Integration von System Manager wird in GovCloud Regionen oder Regionen ohne Outbound-Internetzugang nicht unterstützt.



== Einschränkungen

Einige Funktionen, die in der System Manager-Oberfläche angezeigt werden, werden bei Cloud Volumes ONTAP nicht unterstützt:

* BlueXP Tiering
+
Der BlueXP Tiering Service wird von Cloud Volumes ONTAP nicht unterstützt. Bei der Erstellung von Volumes muss das Tiering von Daten in Objektspeicher direkt aus der Standardansicht von BlueXP eingerichtet werden.

* Tiers
+
Das aggregierte Management (einschließlich lokaler Tiers und Cloud Tiers) wird von System Manager nicht unterstützt. Sie müssen Aggregate direkt über die Standardansicht von BlueXP managen.

* Firmware-Upgrades
+
Automatische Firmware-Updates von der Seite *Cluster > Einstellungen* werden von Cloud Volumes ONTAP nicht unterstützt.



Darüber hinaus wird die rollenbasierte Zugriffssteuerung von System Manager nicht unterstützt.



== Erste Schritte

Öffnen Sie eine Cloud Volumes ONTAP Arbeitsumgebung, und klicken Sie auf die Option Erweiterte Ansicht.

.Schritte
. Wählen Sie im linken Navigationsmenü die Option *Speicherung > Leinwand*.
. Wählen Sie auf der Seite Bildschirm ein Cloud Volumes ONTAP-System aus.
. Suchen Sie im rechten Bereich unter *Services* *System Manager* und wählen Sie *Open* aus.
. Wenn die Bestätigungsmeldung angezeigt wird, lesen Sie sie durch und klicken Sie auf *Schließen*.
. Verwenden Sie System Manager zum Verwalten von Cloud Volumes ONTAP.
. Klicken Sie bei Bedarf auf *zur Standardansicht wechseln*, um zur Standardverwaltung über BlueXP zurückzukehren.




== Hilfe bei der Verwendung von System Manager

Wenn Sie Hilfe bei der Verwendung von System Manager mit Cloud Volumes ONTAP benötigen, finden Sie unter https://docs.netapp.com/us-en/ontap/index.html["ONTAP-Dokumentation"^] Schritt-für-Schritt-Anleitungen. Hier sind einige Links, die helfen könnten:

* https://docs.netapp.com/us-en/ontap/volume-admin-overview-concept.html["Volume- und LUN-Management"^]
* https://docs.netapp.com/us-en/ontap/network-manage-overview-concept.html["Netzwerkmanagement"^]
* https://docs.netapp.com/us-en/ontap/concept_dp_overview.html["Datensicherung"^]

