---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Implementieren Sie Cloud Volumes ONTAP über den Azure Marketplace
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Zur schnellen und einfachen Implementierung von Cloud Volumes ONTAP können Sie die direkte Implementierung von Azure Marketplace nutzen. Über den Azure Marketplace kann schnell mit nur wenigen Klicks implementiert und die Kernfunktionen von Cloud Volumes ONTAP in der Umgebung erkundet werden.

Weitere Informationen zu diesem Angebot finden Sie unter link:concept-azure-mktplace-direct.html["Erfahren Sie mehr über Cloud Volumes ONTAP Angebote auf BlueXP  und dem Markt"].

.Über diese Aufgabe
Das durch die direkte Bereitstellung von Azure Marketplace bereitgestellte Cloud Volumes ONTAP-System verfügt über diese Eigenschaften. Beachten Sie, dass sich die Funktionen einer eigenständigen Instanz, die über den Azure Marketplace bereitgestellt wird, ändern, wenn sie in BlueXP  erkannt wird.

* Die neueste Cloud Volumes ONTAP-Version (9.16.1 oder höher).
* Eine kostenlose Lizenz für Cloud Volumes ONTAP, die auf 500 gib bereitgestellter Kapazität beschränkt ist. Diese Lizenz umfasst keinen NetApp-Support und hat kein Ablaufdatum.
* Zwei Nodes, die im Hochverfügbarkeits-Modus (HA) in einer einzelnen Verfügbarkeitszone (AZ) konfiguriert sind und mit Standardseriennummern bereitgestellt sind. Die Storage Virtual Machines (Storage VMs) werden in einem link:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["Flexibler Orchestrierungsmodus"].
* Standardmäßig ist ein Aggregat für die Instanz erstellt.
* Ein Premium SSD v2 Managed Disk mit einer bereitgestellten Kapazität von 500 gib sowie ein Root- und eine Datenfestplatte.
* Eine Storage-VM mit NFS-, CIFS-, iSCSI- und NVMe/TCP-Datenservices wird implementiert. Sie können keine zusätzlichen Datenspeicher-VMs hinzufügen.
* Lizenzen für NFS, CIFS (SMB), iSCSI, Autonomous Ransomware Protection (ARP), SnapLock und SnapMirror installiert.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["ONTAP temperaturempfindliche Speichereffizienz (TSSE)"^], Volume-Verschlüsselung und externe Schlüsselverwaltung standardmäßig aktiviert.
* Diese Funktionen werden nicht unterstützt:
+
** FabricPool Tiering
** Ändern des Typs der Storage-VM
** Schneller Schreibmodus




.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie über ein gültiges Azure Marketplace-Abonnement verfügen.
* Stellen Sie sicher, dass Sie die Netzwerkanforderungen für ein  in Azure erfüllenlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["HA-Implementierung in einem einzelnen AZ-Setup"]. Siehe link:reference-networking-azure.html["Azure Networking für Cloud Volumes ONTAP einrichten"].
* Ihnen muss eine dieser Azure-Rollen zugewiesen werden, um Cloud Volumes ONTAP implementieren zu können:
+
** Die `contributor` Rolle mit den Standardberechtigungen. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Azure-Dokumentation: In Azure integrierte Rollen"^].
** Eine benutzerdefinierte RBAC-Rolle mit den folgenden Berechtigungen. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Azure-Dokumentation: Benutzerdefinierte Azure Rollen"^].
+
[]
====
"Berechtigungen": [ { "Aktionen": [ "Microsoft.AAD/Register/Action", "Microsoft.Resources/Subscriptions/resourceGroups/write", "Microsoft.Network/loadBalancers/write" Microsoft.Network/virtualNetworks/read" Microsoft.Compute/disks/write" Microsoft.Network/virtualNetworks/subnets/write", "Microsoft.ClassicCompute/virtualMachines/write", "Microsoft.Compute/capacityReservationGroups/deploy/action" Microsoft.Compute/virtualMachines/extensions/write" Microsoft.Network/networkSecurityGroups/write" Microsoft.Compute/virtualMachineScaleSets/write", "Microsoft.ClassicCompute/virtualMachines/networkInterfaces/associatedNetworkityGroups/write", "Microsoft.Network/networkInterfaces/write" Microsoft.Network/virtualNetworks/write" Microsoft.Network/networkSecurityGroups/read" Microsoft.Network/virtualNetworks/subnets/read", "Microsoft.Compute/virtualMachines/write" }

====
+

NOTE: Wenn Sie den Ressourcenanbieter „Microsoft.Storage“ für Ihr Abonnement registriert haben, benötigen Sie keine `Microsoft.AAD/register/action` Berechtigung. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Azure-Dokumentation: Azure permissions for Storage"^].





.Schritte
. Suchen Sie auf der Azure Marketplace Website nach NetApp Produkten.
. Wählen Sie *NetApp Cloud Volumes ONTAP direct*.
. Klicken Sie auf *Create*, um den Bereitstellungsassistenten zu starten.
. Wählen Sie einen Plan aus. Die Liste *Plan* zeigt normalerweise die neuesten Versionen von Cloud Volumes ONTAP an.
. Geben Sie auf der Registerkarte *Grundlagen* folgende Informationen an:
+
** *Abonnement*: Wählen Sie ein Abonnement. Die Bereitstellung wird mit der Abonnementnummer verknüpft.
** *Ressourcengruppe*: Verwenden Sie eine vorhandene Ressourcengruppe oder erstellen Sie eine neue. Ressourcengruppen helfen bei der Zuweisung aller Ressourcen wie Festplatten und Storage-VMs innerhalb einer einzelnen Gruppe für ein Cloud Volumes ONTAP System.
** *Region*: Wählen Sie eine Region aus, die Azure HA-Implementierung in einem einzigen AZ unterstützt. In der Liste werden nur die verfügbaren Regionen angezeigt.
** *Größe*: Wählen Sie eine Speicher-VM-Größe für die unterstützte Premium SSD v2 Managed Disk.
** *Zone*: Wählen Sie eine Zone für die ausgewählte Region aus.
** *Admin-Passwort*: Passwort festlegen. Sie verwenden dieses Admin-Passwort, um sich nach der Bereitstellung beim System anzumelden.
** *Passwort bestätigen*: Geben Sie zur Bestätigung erneut das gleiche Passwort ein.
+
*** Fügen Sie auf der Registerkarte *Netzwerk* ein virtuelles Netzwerk und ein Subnetz hinzu, oder wählen Sie diese aus den Listen aus.
+

NOTE: Um die Beschränkungen von Microsoft Azure einzuhalten, sollten Sie beim Einrichten eines neuen virtuellen Netzwerks ein neues Subnetz erstellen. Ebenso sollten Sie, wenn Sie ein vorhandenes Netzwerk auswählen, ein vorhandenes Subnetz auswählen.

*** Um eine vordefinierte Netzwerksicherheitsgruppe auszuwählen, wählen Sie *Ja* aus. Wählen Sie *Nein*, um eine vordefinierte Sicherheitsgruppe für das Azure-Netzwerk mit den erforderlichen Verkehrsregeln zuzuweisen. Weitere Informationen finden Sie unter link:reference-networking-azure.html#security-group-rules["Sicherheitsgruppenregeln für Azure"].
*** Bestätigen Sie auf der Registerkarte *Advanced*, ob die beiden für diese Bereitstellung erforderlichen Azure-Features gesetzt wurden. Siehe link:task-saz-feature.html["Aktivieren Sie eine Azure-Funktion für einzelne AZ-Implementierungen von Cloud Volumes ONTAP"] und link:task-azure-high-availability-mode.html["Aktivieren Sie den Hochverfügbarkeitsmodus für Cloud Volumes ONTAP in Azure"].
*** Im Register *Tags* können Sie Name und Wertepaare für die Ressourcen oder Ressourcengruppen definieren.
*** Überprüfen Sie auf der Registerkarte *Überprüfen + Erstellen* die Details, und starten Sie die Bereitstellung.






.Nachdem Sie fertig sind
Wählen Sie das Benachrichtigungssymbol aus, um den Fortschritt der Bereitstellung anzuzeigen. Nachdem Cloud Volumes ONTAP bereitgestellt wurde, können Sie die Storage-VM anzeigen, die für Vorgänge aufgeführt ist.

Sobald der Zugriff möglich ist, melden Sie sich mit ONTAP System Manager oder der ONTAP CLI mit den von Ihnen festgelegten Admin-Anmeldeinformationen bei der Storage-VM an. Anschließend können Sie Volumes, LUNs oder Freigaben erstellen und die Storage-Funktionen von Cloud Volumes ONTAP nutzen.



== Fehlerbehebung bei Bereitstellungsproblemen

Cloud Volumes ONTAP Systeme, die direkt über den Azure Marketplace bereitgestellt werden, unterstützen keine NetApp. Sollten während der Implementierung Probleme auftreten, können Sie eigenständig Fehler beheben und beheben.

.Schritte
. Gehen Sie auf der Azure Marketplace-Website zu *Boot Diagnostics > Serial Log*.
. Laden Sie die seriellen Protokolle herunter, und untersuchen Sie sie.
. In der Produktdokumentation und den Artikeln der Knowledge Base (KB) finden Sie weitere Informationen zur Fehlerbehebung.
+
** https://learn.microsoft.com/en-us/partner-center/["Azure Marketplace Dokumentation"]
** https://www.netapp.com/support-and-training/documentation/["NetApp Dokumentation"]
** https://kb.netapp.com/["NetApp KB-Artikel"]






== Die in BlueXP  implementierten Systeme

Sie können die über die direkte Bereitstellung von Azure Marketplace implementierten Cloud Volumes ONTAP Systeme erkennen und diese als Arbeitsumgebungen in BlueXP  managen. Der BlueXP  Connector erkennt die Systeme, fügt sie als Arbeitsumgebungen hinzu, wendet die erforderlichen BlueXP -Lizenzen an und sorgt für die volle Nutzung der Funktionen von BlueXP  für diese Systeme. Die ursprüngliche HA-Konfiguration in einem einzelnen AZ mit PSSD v2 Managed Disks bleibt erhalten, und das System ist in demselben Azure-Abonnement und derselben Ressourcengruppe wie die ursprüngliche Implementierung registriert.

.Über diese Aufgabe
Bei der Erkennung der über die direkte Bereitstellung von Azure Marketplace implementierten Cloud Volumes ONTAP-Systeme führt der BlueXP  Connector die folgenden Aufgaben aus:

* Ersetzt die kostenlosen Lizenzen der entdeckten Systeme als reguläre kapazitätsbasierte link:concept-licensing.html#packages["Freemium-Lizenzen"].
* Behält die bestehenden Funktionen der implementierten Systeme bei und erweitert die zusätzlichen Funktionen von BlueXP , z. B. Funktionen für Datensicherung, Datenmanagement und Sicherheit
* Ersetzt die auf den Knoten installierten Lizenzen durch neue ONTAP Lizenzen für NFS, CIFS (SMB), iSCSI, ARP, SnapLock und SnapMirror.
* Konvertiert die allgemeinen Seriennummern der Nodes in eindeutige Seriennummern.
* Weist den Ressourcen nach Bedarf neue System-Tags zu.
* Konvertiert die dynamischen IP-Adressen der Instanz in statische IP-Adressen.
* Aktiviert die Funktionen von link:task-tiering.html["FabricPool Tiering"], link:task-verify-autosupport.html["AutoSupport"]und link:concept-worm.html["Write-Once-Read-Many"] (WORM) Speicher auf den eingesetzten Systemen. Sie können diese Funktionen bei Bedarf über die BlueXP -Konsole aktivieren.
* Registriert die Instanzen bei den NSS-Konten, die zur Erkennung verwendet werden.
* Aktiviert Funktionen für das Kapazitätsmanagement in link:concept-storage-management.html#capacity-management["Automatischer und manueller Modus"] für die erkannten Systeme.


.Bevor Sie beginnen
Stellen Sie sicher, dass die Implementierung im Azure Marketplace abgeschlossen ist. Der BlueXP -Connector kann die Systeme nur erkennen, wenn die Bereitstellung abgeschlossen ist und zur Erkennung verfügbar ist.


NOTE: Die direkte Bereitstellung von Azure Marketplace unterstützt Instanztypen L8S_v3. BlueXP  unterstützt jedoch diesen Instanztyp nicht für HA-Konfigurationen und wird ihn während der Erkennung nicht korrekt erkennen können.

.Schritte
In BlueXP  befolgen Sie das Standardverfahren zur Erkennung vorhandener Systeme. Siehe link:task-adding-systems.html["Fügen Sie ein vorhandenes Cloud Volumes ONTAP-System zu BlueXP  hinzu"].

.Nachdem Sie fertig sind
Nachdem die Erkennung abgeschlossen ist, können Sie die Systeme anzeigen, die in BlueXP  als Arbeitsumgebungen aufgeführt sind. Sie können verschiedene Verwaltungsaufgaben ausführen, wie link:task-manage-aggregates.html["Erweitern des Aggregats"], , link:task-create-volumes.html["Hinzufügen von Volumes"] link:task-managing-svms-azure.html["Bereitstellung zusätzlicher Storage-VMs"]und link:task-change-azure-vm.html["Ändern der Instanztypen"].

.Weiterführende Links
Weitere Informationen zum Erstellen von Speicher finden Sie in der Dokumentation zu ONTAP:

* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Erstellen Sie Volumes für NFS"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["Erstellen Sie LUNs für iSCSI"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["Erstellen Sie Freigaben für CIFS"^]

