---
sidebar: sidebar 
permalink: task-deploy-cvo-azure-mktplc.html 
keywords: deploy cvo marketplace, marketplace direct cvo deployment, azure marketplace 
summary:  
---
= Implementieren Sie Cloud Volumes ONTAP über den Azure Marketplace
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ab Cloud Volumes ONTAP 9.16.1 können Sie Cloud Volumes ONTAP über Azure Marketplace schnell und einfach über den Azure Marketplace implementieren und wichtige Funktionen in Ihrer Umgebung erkunden.

Weitere Informationen zu diesem Angebot finden Sie unter link:concept-azure-mktplace-direct.html["Erfahren Sie mehr über Cloud Volumes ONTAP Angebote auf BlueXP  und dem Markt"].

.Über diese Aufgabe
Die Instanz von Cloud Volumes ONTAP, die mithilfe der direkten Bereitstellung von Azure Marketplace bereitgestellt wird, verfügt über folgende Eigenschaften:

* Die neueste Cloud Volumes ONTAP-Version (9.16.1 oder höher).
* Eine kostenlose Lizenz für Cloud Volumes ONTAP, die auf 500 gib bereitgestellter Kapazität beschränkt ist. Diese Lizenz umfasst keinen NetApp-Support und hat kein Ablaufdatum.
* Zwei Nodes, die im Hochverfügbarkeits-Modus (HA) in einer einzelnen Verfügbarkeitszone (AZ) konfiguriert sind und mit Standardseriennummern bereitgestellt sind. Die Storage Virtual Machines (SVMs) werden in einemlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["Flexibler Orchestrierungsmodus"]
* Standardmäßig ist ein Aggregat für die Instanz erstellt.
* Ein Premium SSD v2 Managed Disk mit einer bereitgestellten Kapazität von 500 gib sowie ein Root- und eine Datenfestplatte.
* Eine einzige Data SVM mit NFS-, CIFS-, iSCSI- und NVMe/TCP-Datenservices implementiert. Keine Bereitstellung für zusätzliche SVMs
* Lizenzen für NFS, CIFS (SMB), iSCSI, Anti-Ransomware (ARW), SnapLock und SnapMirror, installiert auf die Standard-Seriennummern.
* https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html["ONTAP temperaturempfindliche Speichereffizienz (TSSE)"^], Volume-Verschlüsselung und externe Schlüsselverwaltung standardmäßig aktiviert.
* Diese Funktionen werden nicht unterstützt:
+
** FabricPool Tiering
** Ändern des Instanztyps
** Schneller Schreibmodus




.Bevor Sie beginnen
* Stellen Sie sicher, dass Sie über ein gültiges Azure Marketplace-Abonnement verfügen.
* Stellen Sie sicher, dass Sie die Netzwerkanforderungen für ein  in Azure erfüllenlink:concept-ha-azure.html#ha-single-availability-zone-configuration-with-shared-managed-disks["HA-Implementierung in einem einzelnen AZ-Setup"]. Siehe link:reference-networking-azure.html["Azure Networking für Cloud Volumes ONTAP einrichten"].
* Ihnen muss eine dieser Azure-Rollen zugewiesen werden, um Cloud Volumes ONTAP implementieren zu können:
+
** Die `contributor` Rolle mit den Standardberechtigungen. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles["Azure-Dokumentation: In Azure integrierte Rollen"^].
** Eine benutzerdefinierte RBAC-Rolle mit den folgenden Berechtigungen. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles["Azure-Dokumentation: Benutzerdefinierte Azure Rollen"^].
+
[]
====
"Berechtigungen": [ { "Aktionen": [ "Microsoft.AAD/Register/Action", "Microsoft.Resources/Subscriptions/resourceGroups/write", "Microsoft.Network/loadBalancers/write" Microsoft.Network/virtualNetworks/read" Microsoft.Compute/disks/write" Microsoft.Network/virtualNetworks/subnets/write", "Microsoft.ClassicCompute/virtualMachines/write", "Microsoft.Compute/capacityReservationGroups/deploy/action" Microsoft.Compute/virtualMachines/extensions/write" Microsoft.Network/networkSecurityGroups/write" Microsoft.Compute/virtualMachineScaleSets/write", "Microsoft.ClassicCompute/virtualMachines/networkInterfaces/associatedNetworkityGroups/write", "Microsoft.Network/networkInterfaces/write" Microsoft.Network/virtualNetworks/write" Microsoft.Network/networkSecurityGroups/read" Microsoft.Network/virtualNetworks/subnets/read", "Microsoft.Compute/virtualMachines/write" }

====
+

NOTE: Wenn Sie den Ressourcenanbieter „Microsoft.Storage“ für Ihr Abonnement registriert haben, benötigen Sie keine `Microsoft.AAD/register/action` Berechtigung. Weitere Informationen finden Sie im https://learn.microsoft.com/en-us/azure/role-based-access-control/permissions/storage["Azure-Dokumentation: Azure permissions for Storage"^].





.Schritte
. Suchen Sie auf der Azure Marketplace Website nach NetApp Produkten.
. Wählen Sie *NetApp Cloud Volumes ONTAP direct*.
. Klicken Sie auf *Create*, um den Bereitstellungsassistenten zu starten.
. Wählen Sie einen Plan aus. Die Liste *Plan* zeigt normalerweise die neuesten Versionen von Cloud Volumes ONTAP an.
. Geben Sie auf der Registerkarte *Grundlagen* folgende Informationen an:
+
** *Abonnement*: Wählen Sie ein Abonnement. Die Bereitstellung wird mit der Abonnementnummer verknüpft.
** *Ressourcengruppe*: Verwenden Sie eine vorhandene Ressourcengruppe oder erstellen Sie eine neue. Ressourcengruppen helfen bei der Zuweisung aller Ressourcen, z. B. Festplatten und SVMs, innerhalb einer einzelnen Gruppe für eine Cloud Volumes ONTAP Instanz.
** *Region*: Wählen Sie eine Region aus, die Azure HA-Implementierung in einem einzigen AZ unterstützt. In der Liste werden nur die verfügbaren Regionen angezeigt.
** *Größe*: Wählen Sie eine SVM-Größe für die unterstützte Premium SSD v2 Managed Disk aus.
** *Zone*: Wählen Sie eine Zone für die ausgewählte Region aus.
** *Admin-Passwort*: Passwort festlegen. Sie verwenden dieses Admin-Passwort, um sich nach der Bereitstellung beim System anzumelden.
** *Passwort bestätigen*: Geben Sie zur Bestätigung erneut das gleiche Passwort ein.
+
*** Fügen Sie auf der Registerkarte *Netzwerk* ein virtuelles Netzwerk und ein Subnetz hinzu, oder wählen Sie diese aus den Listen aus.
+

NOTE: Um die Beschränkungen von Microsoft Azure einzuhalten, sollten Sie beim Einrichten eines neuen virtuellen Netzwerks ein neues Subnetz erstellen. Ebenso sollten Sie, wenn Sie ein vorhandenes Netzwerk auswählen, ein vorhandenes Subnetz auswählen.

*** Um eine vordefinierte Netzwerksicherheitsgruppe auszuwählen, wählen Sie *Ja* aus. Wählen Sie *Nein*, um eine vordefinierte Sicherheitsgruppe für das Azure-Netzwerk mit den erforderlichen Verkehrsregeln zuzuweisen. Weitere Informationen finden Sie unter link:reference-networking-azure.html#security-group-rules["Sicherheitsgruppenregeln für Azure"].
*** Bestätigen Sie auf der Registerkarte *Advanced*, ob die beiden für diese Bereitstellung erforderlichen Azure-Features gesetzt wurden. Siehe link:task-saz-feature.html["Aktivieren Sie eine Azure-Funktion für einzelne AZ-Implementierungen von Cloud Volumes ONTAP"] und link:task-azure-high-availability-mode.html["Aktivieren Sie den Hochverfügbarkeitsmodus für Cloud Volumes ONTAP in Azure"].
*** Im Register *Tags* können Sie Name und Wertepaare für die Ressourcen oder Ressourcengruppen definieren.
*** Überprüfen Sie auf der Registerkarte *Überprüfen + Erstellen* die Details, und starten Sie die Bereitstellung.






.Nachdem Sie fertig sind
Wählen Sie das Benachrichtigungssymbol aus, um den Fortschritt der Bereitstellung anzuzeigen. Nach der Implementierung von Cloud Volumes ONTAP können Sie die aufgeführte SVM für die Vorgänge anzeigen.

Sobald der Zugriff möglich ist, melden Sie sich über ONTAP System Manager oder die ONTAP CLI mit den von Ihnen festgelegten Admin-Anmeldeinformationen bei der SVM an. Anschließend können Sie Volumes, LUNs oder Freigaben erstellen und die Storage-Funktionen von Cloud Volumes ONTAP nutzen.



== Fehlerbehebung

Cloud Volumes ONTAP-Implementierungen, die direkt über den Azure Marketplace erstellt wurden, bieten keinen Support von NetApp. Sollten während der Implementierung Probleme auftreten, können Sie eigenständig Fehler beheben und beheben.

.Schritte
. Gehen Sie auf der Azure Marketplace-Website zu *Boot Diagnostics > Serial Log*.
. Laden Sie die seriellen Protokolle herunter, und untersuchen Sie sie.
. In der Produktdokumentation und den Artikeln der Knowledge Base (KB) finden Sie weitere Informationen zur Fehlerbehebung.
+
** https://learn.microsoft.com/en-us/partner-center/["Azure Marketplace Dokumentation"]
** https://www.netapp.com/support-and-training/documentation/["NetApp Dokumentation"]
** https://kb.netapp.com/["NetApp KB-Artikel"]




.Weiterführende Links
Weitere Informationen zum Erstellen von Speicher finden Sie in der Dokumentation zu ONTAP:

* https://docs.netapp.com/us-en/ontap/volumes/create-volume-task.html["Erstellen Sie Volumes für NFS"^]
* https://docs.netapp.com/us-en/ontap-cli/lun-create.html["Erstellen Sie LUNs für iSCSI"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["Erstellen Sie Freigaben für CIFS"^]

