= Ende der Verfügbarkeit für Node-basierte Lizenzen
:allow-uri-read: 




=== Ende der Verfügbarkeit für Node-basierte Lizenzen

NetApp plant das Ende der Verfügbarkeit (EOA) und das Ende des Supports (EOS) für die Node-basierte Cloud Volumes ONTAP Lizenzierung. Ab dem 11. November 2024 wurde die begrenzte Verfügbarkeit von Node-basierten Lizenzen eingestellt. Der Support für Node-basierte Lizenzierung endet am 31. Dezember 2024. Nachdem Ihre Node-basierten Lizenzen nicht mehr erhältlich sind, sollten Sie die kapazitätsbasierte Lizenzierung mithilfe des BlueXP  Lizenzkonvertierungs-Tools starten.

Wenn NetApp Sie ein jährliches oder längerfristiges Programm nutzen möchten, sollten Sie Ihren NetApp Ansprechpartner vor dem EOA-Datum oder dem Ablaufdatum der Lizenz kontaktieren. So sollten Sie sicherstellen, dass die Voraussetzungen für die Transition gegeben sind. Wenn Sie keinen langfristigen Vertrag für einen Cloud Volumes ONTAP-Node haben und Ihr System mit einem PAYGO-Abonnement (On-Demand Pay-as-you-go) ausführen, ist es wichtig, die Konvertierung vor dem EOS-Datum zu planen. Sowohl für langfristige Verträge als auch für PAYGO Abonnements können Sie das BlueXP  Lizenzkonvertierungstool für eine nahtlose Konvertierung verwenden.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Ende der Verfügbarkeit von Node-basierten Lizenzen"^] https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-convert-node-capacity.html["Konvertieren Sie eine Node-basierte Cloud Volumes ONTAP Lizenz in eine kapazitätsbasierte Lizenz"^]



=== Keine Node-basierten Implementierungen mehr aus BlueXP 

Die Option, Cloud Volumes ONTAP Systeme mit Node-basierten Lizenzen zu implementieren, ist von BlueXP  veraltet. Außer für einige Sonderfälle können Sie keine Node-basierten Lizenzen für Cloud Volumes ONTAP-Implementierungen bei einem Cloud-Provider verwenden.

NetApp erkennt die folgenden besonderen Lizenzierungsanforderungen bei der Einhaltung der vertraglichen Verpflichtungen und betrieblichen Anforderungen und unterstützt in den folgenden Situationen weiterhin Node-basierte Lizenzen:

* Kunden des öffentlichen Sektors in den USA
* Bereitstellungen im privaten Modus
* China-Region Bereitstellung von Cloud Volumes ONTAP in AWS
* Wenn Sie über eine gültige, nicht abgelaufene by-Node-Lizenz (BYOL-Lizenz) verfügen,


https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Ende der Verfügbarkeit von Node-basierten Lizenzen"^]



=== Hinzufügen einer Cold-Tier für Cloud Volumes ONTAP-Daten auf Azure Blob-Storage

Mit BlueXP  können Sie jetzt eine kalte Tier auswählen, um die inaktiven Kapazitäts-Tiers auf Azure Blob Storage zu speichern. Wenn Sie die Cold-Tier zu den vorhandenen Tiers für heiße und kalte Daten hinzufügen, profitieren Sie von einer kostengünstigeren Storage-Option und einer höheren Kosteneffizienz.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html#data-tiering-in-azure["Daten-Tiering in Azure"^]



=== Option, den öffentlichen Zugriff auf Storage-Konto für Azure zu beschränken

Sie haben nun die Möglichkeit, den öffentlichen Zugriff auf Ihr Storage-Konto für Cloud Volumes ONTAP-Systeme auf Azure einzuschränken. Wenn Sie den Zugriff deaktivieren, können Sie Ihre private IP-Adresse auch im selben vnet vor der Offenlegung schützen, falls die Sicherheitsrichtlinien Ihres Unternehmens eingehalten werden müssen. Diese Option deaktiviert auch das Daten-Tiering für Ihre Cloud Volumes ONTAP-Systeme und ist sowohl für einzelne Nodes als auch für Hochverfügbarkeitspaare anwendbar.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html#security-group-rules["Regeln für Sicherheitsgruppen"^].



=== WORM-Aktivierung nach der Bereitstellung von Cloud Volumes ONTAP

Sie können nun WORM-Storage (Write Once, Read Many) auf einem bestehenden Cloud Volumes ONTAP System mithilfe von BlueXP  aktivieren. Mit dieser Funktionalität erhalten Sie die Flexibilität, WORM in einer Arbeitsumgebung zu aktivieren, auch wenn WORM während seiner Erstellung nicht aktiviert wurde. Sobald diese Option aktiviert ist, können Sie WORM nicht mehr deaktivieren.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html#enabling-worm-on-a-cloud-volumes-ontap-working-environment["Aktivierung von WORM in einer Cloud Volumes ONTAP Arbeitsumgebung"^]
